/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScreenCandidateIdRouteImport } from './routes/screen.$candidateId'
import { Route as ApplyJobIdRouteImport } from './routes/apply.$jobId'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppCandidatesRouteImport } from './routes/_authenticated/app.candidates'
import { Route as AuthenticatedAppJobsNewRouteImport } from './routes/_authenticated/app.jobs.new'
import { Route as AuthenticatedAppJobsJobIdRouteImport } from './routes/_authenticated/app.jobs.$jobId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenCandidateIdRoute = ScreenCandidateIdRouteImport.update({
  id: '/screen/$candidateId',
  path: '/screen/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyJobIdRoute = ApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCandidatesRoute =
  AuthenticatedAppCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppJobsNewRoute = AuthenticatedAppJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppJobsJobIdRoute =
  AuthenticatedAppJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/screen/$candidateId': typeof ScreenCandidateIdRoute
  '/app/candidates': typeof AuthenticatedAppCandidatesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/app/jobs/new': typeof AuthenticatedAppJobsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/screen/$candidateId': typeof ScreenCandidateIdRoute
  '/app/candidates': typeof AuthenticatedAppCandidatesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/app/jobs/new': typeof AuthenticatedAppJobsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/screen/$candidateId': typeof ScreenCandidateIdRoute
  '/_authenticated/app/candidates': typeof AuthenticatedAppCandidatesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/_authenticated/app/jobs/new': typeof AuthenticatedAppJobsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/apply/$jobId'
    | '/screen/$candidateId'
    | '/app/candidates'
    | '/app/'
    | '/app/jobs/$jobId'
    | '/app/jobs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/apply/$jobId'
    | '/screen/$candidateId'
    | '/app/candidates'
    | '/app'
    | '/app/jobs/$jobId'
    | '/app/jobs/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/apply/$jobId'
    | '/screen/$candidateId'
    | '/_authenticated/app/candidates'
    | '/_authenticated/app/'
    | '/_authenticated/app/jobs/$jobId'
    | '/_authenticated/app/jobs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApplyJobIdRoute: typeof ApplyJobIdRoute
  ScreenCandidateIdRoute: typeof ScreenCandidateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen/$candidateId': {
      id: '/screen/$candidateId'
      path: '/screen/$candidateId'
      fullPath: '/screen/$candidateId'
      preLoaderRoute: typeof ScreenCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$jobId': {
      id: '/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof ApplyJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/candidates': {
      id: '/_authenticated/app/candidates'
      path: '/candidates'
      fullPath: '/app/candidates'
      preLoaderRoute: typeof AuthenticatedAppCandidatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/jobs/new': {
      id: '/_authenticated/app/jobs/new'
      path: '/jobs/new'
      fullPath: '/app/jobs/new'
      preLoaderRoute: typeof AuthenticatedAppJobsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/jobs/$jobId': {
      id: '/_authenticated/app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/app/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedAppJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCandidatesRoute: typeof AuthenticatedAppCandidatesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppJobsJobIdRoute: typeof AuthenticatedAppJobsJobIdRoute
  AuthenticatedAppJobsNewRoute: typeof AuthenticatedAppJobsNewRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCandidatesRoute: AuthenticatedAppCandidatesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppJobsJobIdRoute: AuthenticatedAppJobsJobIdRoute,
  AuthenticatedAppJobsNewRoute: AuthenticatedAppJobsNewRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApplyJobIdRoute: ApplyJobIdRoute,
  ScreenCandidateIdRoute: ScreenCandidateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
